let gameData = {
	"Counting": [
		{"english": "One", "korean": "Hah Nah"},
		{"english": "Two", "korean": "Dul"},
		{"english": "Three", "korean": "Set"},
		{"english": "Four", "korean": "Net"},
		{"english": "Five", "korean": "Dah Suht"},
		{"english": "Six", "korean": "Yuh Suht"},
		{"english": "Seven", "korean": "Il Gohp"},
		{"english": "Eight", "korean": "Yuh Duhl"},
		{"english": "Nine", "korean": "Ah Hohp"},
		{"english": "Ten", "korean": "Yuhl"}
	],
	"Hand Techniques / Soo Ki": [
		{"english": "Straight Punch", "korean": "Juhng Gwuhn"},
		{"english": "Palm", "korean": "Pyuhng Soo"},
		{"english": "Spear-hand", "korean": "Gwahn Soo"},
		{"english": "Straight Spear-hand", "korean": "Jihk Gwahn Soo"},
		{"english": "Reverse Knife-hand", "korean": "Yuhk Soo Doh"},
		{"english": "Circle Knife-hand", "korean": "Hweh Juhn Soo Doh"},
		{"english": "Back-fist", "korean": "Gahk Gwuhn"},
		{"english": "Elbow", "korean": "Pahl Kum Chi"},
		{"english": "Praying Mantis Fist", "korean": "Sah Mah Gwi Gwuhn"},
		{"english": "Back-hand", "korean": "Sohn Deung Pyuhng Soo"},
		{"english": "Reverse Palm", "korean": "Yuhm Pyuhng Soo"},
		{"english": "Double Palm", "korean": "Ssang Pyuhng Soo"},
		{"english": "Double Knife-hand", "korean": "Ssang Soo Doh"},
		{"english": "Tiger's mouth fist", "korean": "Hoh Goo Gwuhn"},
		{"english": "Tiger claw", "korean": "Hoh Gwuhn"},
		{"english": "Little finger Hammer fist", "korean": "Baek Pahl Ki Gwuhn"},
		{"english": "One-finger fist", "korean": "Il Ji Gwuhn"},
		{"english": "Middle-knuckle fist", "korean": "Joong Chi Gwuhn"},
		{"english": "Thumb", "korean": "Uhn Ji"},
		{"english": "Four-finger Knuckle fist", "korean": "Sah Ji Gwuhn"},
		{"english": "One finger", "korean": "Il Ji"},
		{"english": "Two fingers", "korean": "Ee Ji"},
		{"english": "Five fingers", "korean": "Oh Ji"},
		{"english": "Praying Mantis block", "korean": "Sah Mah Gwi Mahk Ki"},
		{"english": "Cross block", "korean": "X Mahk Ki"},
		{"english": "Four Directional Blocking", "korean": "Ship Ja Mahk Ki"}
	]
};