let gameData = {
	"Counting (Numbers)": [
		{"values":{"english": "One", "korean": "Hah Nah"}},
		{"values":{"english": "Two", "korean": "Dul"}},
		{"values":{"english": "Three", "korean": "Set"}},
		{"values":{"english": "Four", "korean": "Net"}},
		{"values":{"english": "Five", "korean": "Dah Suht"}},
		{"values":{"english": "Six", "korean": "Yuh Suht"}},
		{"values":{"english": "Seven", "korean": "Il Gohp"}},
		{"values":{"english": "Eight", "korean": "Yuh Duhl"}},
		{"values":{"english": "Nine", "korean": "Ah Hohp"}},
		{"values":{"english": "Ten", "korean": "Yuhl"}}
	],
	"Counting (Ordering)": [
		{"values":{"english": "First", "korean": "Il"}},
		{"values":{"english": "Second", "korean": "Ee"}},
		{"values":{"english": "Third", "korean": "Sahm"}},
		{"values":{"english": "Fourth", "korean": "Sah"}},
		{"values":{"english": "Fifth", "korean": "Oh"}},
		{"values":{"english": "Sixth", "korean": "Yook"}},
		{"values":{"english": "Seventh", "korean": "Chil"}},
		{"values":{"english": "Eighth", "korean": "Pahl"}},
		{"values":{"english": "Ninth", "korean": "Gu"}},
		{"values":{"english": "Tenth", "korean": "Ship"}}
	],
	"Directions, Relationships and Movements": [
		{"values":{"korean": "Ahn", "english": "Inside"}},
		{"values":{"korean": "Ahp", "english": "Front"}},
		{"values":{"korean": "Yuhp", "english": "Side"}},
		{"values":{"korean": "Dwee / Dee", "english": "Back"}},
		{"values":{"korean": "Dee Uh", "english": "Jumping"}},
		{"values":{"korean": "Doh Rah", "english": "Spinning"}},
		{"values":{"korean": "Hweh Juhn", "english": "Turning / Rotating"}},
		{"values":{"korean": "Sahng", "english": "High"}},
		{"values":{"korean": "Joong", "english": "Middle"}},
		{"values":{"korean": "Hah", "english": "Low"}},
		{"values":{"korean": "Yahng", "english": "Both"}},
		{"values":{"korean": "Ssang", "english": "Double"}},
		{"values":{"korean": "Yuhk", "english": "Reverse"}},
	],
	"Parts of the Body": [
		{"values":{"korean": "Ahn Sohn Mohk", "english": "Inside Wrist Joint"}},
		{"values":{"korean": "Bahl", "english": "Foot"}},
		{"values":{"korean": "Bahl Deung", "english": "Foot Top"}},
		{"values":{"korean": "Bahl Mohk", "english": "Foot Joint (Ankle)"}},
		{"values":{"korean": "Moo Reup", "english": "Knee"}},
		{"values":{"korean": "Bahl Koom Chi", "english": "Heel"}},
		{"values":{"korean": "Sohn", "english": "Hand"}},
		{"values":{"korean": "Sohn Mohk", "english": "Wrist"}},
		{"values":{"korean": "Dah Ree", "english": "Leg"}},
		{"values":{"korean": "Uh Kae", "english": "Shoulder"}},
		{"values":{"korean": "Pahl Koom Chi", "english": "Elbow"}},
	],
	"Titles and Ranks": [
		{"values":{"english": "National Martial Arts Teacher", "korean": "Kuk Sa Nim"}},
		{"values":{"english": "Chief Master", "korean": "Chohng Kwahn Jahng Nim"}},
		{"values":{"english": "9th Degree Black Belt", "korean": "Su Suhk Kwahn Jahng Nim"}},
		{"values":{"english": "8th Degree Black Belt", "korean": "Suhn Im Kwahn Jahng Nim"}},
		{"values":{"english": "7th Degree Black Belt", "korean": "Ji Do Kwahn Jahng Nim"}},
		{"values":{"english": "6th Degree Black Belt", "korean": "Joo Im Kwahn Jahng Nim"}},
		{"values":{"english": "5th Degree Black Belt", "korean": "Pyung Kwahn Jahng Nim"}},
		{"values":{"english": "4th Degree Black Belt", "korean": "Sa Bum Nim"}},
		{"values":{"english": "3rd Degree Black Belt", "korean": "Pu Sa Bum Nim"}},
		{"values":{"english": "2nd Degree Black Belt", "korean": "Kyo Sa Nim"}},
		{"values":{"english": "1st Degree Black Belt", "korean": "Jo Kyo Nim"}},
		{"values":{"english": "Black-Brown Belt", "korean": "Dahn Boh"}},
		{"values":{"english": "Brown Belt", "korean": "Ja Di"}},
		{"values":{"english": "Red Belt", "korean": "Hohng Di"}},
		{"values":{"english": "Blue Belt", "korean": "Chuhng Di"}},
		{"values":{"english": "Yellow Belt", "korean": "Noh Rahng Di"}},
		{"values":{"english": "White Belt", "korean": "Hin Di"}}
	],
	"Names": [
		{"values":{"english": "National (Korean) Martial Arts Association", "korean": "Kuk Sool Won"}},
		{"values":{"english": "Royal Court Martial Arts", "korean": "Koong-Joong Mu Sool"}},
		{"values":{"english": "Buddhist Martial Arts", "korean": "Bool-Kyo Mu Sool"}},
		{"values":{"english": "Tribal (Family) Martial Arts", "korean": "Sah-Doh Mu Sool"}},
		{"values":{"english": "National Flag", "korean": "Kuk Ki"}},
		{"values":{"english": "Association Flag", "korean": "Won Ki"}},
		{"values":{"english": "Martial Arts Student", "korean": "Jae Jah"}},
		{"values":{"english": "Black Belt Holder", "korean": "Yoo Dahn Jah"}}
	],
	"Hand Techniques / Soo Ki": [
		{"values":{"english": "Straight Punch", "korean": "Juhng Gwuhn"}},
		{"values":{"english": "Palm", "korean": "Pyuhng Soo"}},
		{"values":{"english": "Spear-hand", "korean": "Gwahn Soo"}},
		{"values":{"english": "Straight Spear-hand", "korean": "Jihk Gwahn Soo"}},
		{"values":{"english": "Reverse Knife-hand", "korean": "Yuhk Soo Doh"}},
		{"values":{"english": "Circle Knife-hand", "korean": "Hweh Juhn Soo Doh"}},
		{"values":{"english": "Back-fist", "korean": "Gahk Gwuhn"}},
		{"values":{"english": "Elbow", "korean": "Pahl Kum Chi"}},
		{"values":{"english": "Praying Mantis Fist", "korean": "Sah Mah Gwi Gwuhn"}},
		{"values":{"english": "Back-hand", "korean": "Sohn Deung Pyuhng Soo"}},
		{"values":{"english": "Reverse Palm", "korean": "Yuhk Pyuhng Soo"}},
		{"values":{"english": "Double Palm", "korean": "Ssang Pyuhng Soo"}},
		{"values":{"english": "Double Knife-hand", "korean": "Ssang Soo Doh"}},
		{"values":{"english": "Tiger's mouth fist", "korean": "Hoh Goo Gwuhn"}},
		{"values":{"english": "Tiger claw", "korean": "Hoh Gwuhn"}},
		{"values":{"english": "Little finger Hammer fist", "korean": "Baek Pahl Ki Gwuhn"}},
		{"values":{"english": "One-finger fist", "korean": "Il Ji Gwuhn"}},
		{"values":{"english": "Middle-knuckle fist", "korean": "Joong Chi Gwuhn"}},
		{"values":{"english": "Thumb", "korean": "Uhm Ji"}},
		{"values":{"english": "Four-finger Knuckle fist", "korean": "Sah Ji Gwuhn"}},
		{"values":{"english": "One finger", "korean": "Il Ji"}},
		{"values":{"english": "Two fingers", "korean": "Ee Ji"}},
		{"values":{"english": "Five fingers", "korean": "Oh Ji"}},
		{"values":{"english": "Praying Mantis block", "korean": "Sah Mah Gwi Mahk Ki"}},
		{"values":{"english": "Cross block", "korean": "X Mahk Ki"}},
		{"values":{"english": "Four Directional Blocking", "korean": "Ship Ja Mahk Ki"}}
	],
	"Kicking Techniques / Johk Sool": [
		{"values":{"english": "Straight-leg Kick", "korean": "Ahp Cha Ohl Li Ki"}},
		{"values":{"english": "Font Kick", "korean": "Ahp Cha Ki"}},
		{"values":{"english": "Knee Kick", "korean": "Moo Reup Cha Ki"}},
		{"values":{"english": "Inside Kick", "korean": "Ahn Dah Ree Cha Ki"}},
		{"values":{"english": "Outside Kick", "korean": "Bah Gaht Dah Ree Cha Ki"}},
		{"values":{"english": "Round-house Kick", "korean": "Bahl Deung Cha Ki"}},
		{"values":{"english": "Side Kick", "korean": "Yuhp Cha Ki"}},
		{"values":{"english": "Back Kick", "korean": "Dee Cha Ki"}},
		{"values":{"english": "Hook Kick", "korean": "Bahl Koom Chi Cha Ki"}},
		{"values":{"english": "Axe Kick", "korean": "Jik Uh Cha Ki"}},
		{"values":{"english": "Reverse Round-house Kick", "korean": "Yuhk Bahl Deung Cha Ki"}},
		{"values":{"english": "Turn Inside Heel Kick", "korean": "Ahn Koom Chi Dohl Li Ki"}},
		{"values":{"english": "Side-front Kick", "korean": "Yuhp Jik Ki"}},
		{"values":{"english": "Turn Back Side Kick", "korean": "Dee Doh Rah Yuhp Cha Ki"}},
		{"values":{"english": "High Spinning Kick", "korean": "Sahng Dahn Doh Rah Cha Ki"}},
		{"values":{"english": "Low Spin Kick", "korean": "Hah Dahn Doh Rah Cha Ki"}}
	],
	"Nak Bup / Falling Principles": [
		{"values":{"english": "Font Fall", "korean": "Ahp Nak Bup"}},
		{"values":{"english": "Back Fall", "korean": "Dee Nak Bup"}},
		{"values":{"english": "Yuhp Nak Bup", "korean": "Side Fall"}},
		{"values":{"english": "Front-side Fall", "korean": "Ahp Yuhp Nak Bup"}},
		{"values":{"english": "Rolling Fall", "korean": "Hweh Juhn Nak Bup"}},
		{"values":{"english": "Two Hand Cart-wheel", "korean": "Doo Sohn Poong Cha"}},
		{"values":{"english": "One Hand Cart-wheel", "korean": "Hahn Sohn Poong Cha"}},
		{"values":{"english": "Elbow Cart-wheel", "korean": "Pahl Kum Chi Poong Cha"}},
		{"values":{"english": "Aerial", "korean": "Gong Joong Poong Cha"}},
		{"values":{"english": "Hand-Spring", "korean": "Doo Sohn Ahp Poong Cha"}},
		{"values":{"english": "Cat Roll", "korean": "Goh Yahng Ee Nak Bup"}},
		{"values":{"english": "High Rolling Fall", "korean": "Gong Joong Hweh Juhn Nak Bup"}},
		{"values":{"english": "Front Flip", "korean": "Ahp Gong Joong Hweh Juhn Nak Bup"}},
		{"values":{"english": "Back Flip", "korean": "Dee Gong Joong Hweh Juhn Nak Bup"}}
	],
	"Maek Chi Ki (Order)": [
		{"values":{"english": "One", "korean": "Yuhl Gyhul Hyul"}},
		{"values":{"english": "Two", "korean": "Soo Sahm Ri Hyul"}},
		{"values":{"english": "Three", "korean": "Chuhn Boo Hyul"}},
		{"values":{"english": "Four", "korean": "Geuk Chun Hyul"}},
		{"values":{"english": "Five", "korean": "Hohn Soo Hyul"}},
		{"values":{"english": "Six", "korean": "Gaek Joo In"}},
		{"values":{"english": "Seven", "korean": "Hohn Soo Hyul"}},
		{"values":{"english": "Eight", "korean": "Dae Po Hyul"}},
		{"values":{"english": "Nine", "korean": "Um Kyo"}},
		{"values":{"english": "Ten", "korean": "Goo Mi Hyul"}},
		{"values":{"english": "Eleven", "korean": "Yuhm Chuhn Hyul"}},
		{"values":{"english": "Twelve", "korean": "Jahng Moon Hyul"}},
		{"values":{"english": "Thirteen", "korean": "Ah Moon Hyul"}},
		{"values":{"english": "Fourteen", "korean": "Shin Jhung Hyul"}},
		{"values":{"english": "Fifteen", "korean": "Yoo Geun Hyul"}},
	],
	"Maek Cha Ki (Order)": [
		{"values":{"english": "One", "korean": "Sahm Um Kyo Hyul"}},
		{"values":{"english": "Two", "korean": "Dohk Bi Hyul"}},
		{"values":{"english": "Three", "korean": "Wee Joong Hyul"}},
		{"values":{"english": "Four", "korean": "Hyul Hae Hyul"}},
		{"values":{"english": "Five", "korean": "Jang Moon Hyul"}},
		{"values":{"english": "Six", "korean": "Geuk Chuhn Hyul"}},
		{"values":{"english": "Seven", "korean": "Ki Hae Hyul"}},
		{"values":{"english": "Eight", "korean": "Goo Mi Hyul"}},
		{"values":{"english": "Nine", "korean": "Yuhm Chuhn Hyul"}},
		{"values":{"english": "Ten", "korean": "Hohn Soo Hyul"}},
		{"values":{"english": "Eleven", "korean": "Yoo Geun Hyul"}},
		{"values":{"english": "Twelve", "korean": "Ah Moon Hyul"}},
		{"values":{"english": "Thirteen", "korean": "Gaek Joo In"}},
		{"values":{"english": "Fourteen", "korean": "Dae Choo Hyul"}},
		{"values":{"english": "Fifteen", "korean": "Yang Neung Chuhn Hyul"}},
	],
};